language: ruby

rvm:
  - ree

before_install:
  - sudo add-apt-repository -y http://www.scriptroute.org/debian/ stable main
  - sudo apt-get -qq update
  - sudo apt-get install -qq scriptroute
  - sudo apt-get install -qq pchar

script: ./script.sh