#!/bin/sh

set -e

url=https://s3.amazonaws.com/paperplanes-cache/chrome.zip
host=s3.amazonaws.com

if [ "$1" != "" ]; then
  ip=$(host $1 | awk '/has address/ { print $4 }')
  
  echo "Downloading from overridden $host with $1 ($ip)"
  curl -o /dev/null --resolve "$host:443:$ip" $url
  
  traceroute -m 19 -A $ip
else
  echo "Downloading from $host"

  curl -o /dev/null $url

  traceroute -m 19 -A $host
fi


